### PR TITLE
trying to fix #195 by making `Lwt_io.common#close` idempotent

### LINKED ISSUE #195: strange failure on timeouted sub-process
```ocaml
Lwt_process.with_process_full ~timeout:3. ("sleep", [| "sleep"; "5" |]) 
  (fun p -> Lwt_io.read p#stdout )
|> Lwt_main.run;;
```

This piece of code should, I think, read and return "" after 3 seconds (the sub-process timeouts). What I get instead is an uncaught `CamlinternalLazy.Undefined`.

### PR DESCRIPTION
**Pull request by c-cube**
Test case

```ocaml
(*

  ocamlopt -I _build/src/core -I _build/src/unix -g -inline 0 bigarray.cmxa unix.cmxa lwt.cmxa lwt-unix.cmxa truc.ml -o truc ; ./truc

  *)

open Lwt;;

Lwt_process.with_process_in
  ~timeout:1. ("sleep", [| "sleep"; "2" |]) 
    (fun p ->
      Lwt.catch
        (fun () -> Lwt_io.read p#stdout)
        (fun _ -> Lwt.return ""))
  >>= Lwt_io.printlf "read %s"
  |> Lwt_main.run;;
```
seems to work, now (that is, the callback tries to read `p#stdout` and gets an exception about a closed channel; not the unexpected `Lazy.Undefined`).

### CODE REVIEW

**Comment by Drup** [comment]
Can you add your test too ?

**Comment by c-cube** [comment]
The test fails on the previous commit.

**Comment by c-cube** [comment]
Any news on this?

**Comment by Drup** [comment]
Sorry for the wait!

**Pull request merged**
