### PR TITLE
some discover.ml fixes

### PR DESCRIPTION
**Pull request by oandrieu**
addresses #747

### CODE REVIEW

**Comment by aantron** [comment]
IIRC, on at least one platform (Androd), linking fails when `-lpthread` is passed, but the symbols needed by Lwt are still available in the standard libraries chosen by the linker, so that's why we try to link without any flags first.

We could special-case this for Android only. I'll look through the history of Lwt in git and GitHub for any other platforms on which this could be important.

**Comment by aantron** [comment]
To summarize my understanding at the moment, we have some platforms on which `-lpthread` *must not* be passed, and other platforms or setups on which `-lpthread` *should* be passed to avoid `discover.ml` searching for libraries and finding the wrong ones.

After this PR, I'll add a comment to this part of `discover.ml` about all the conditions.

**Comment by aantron** [comment]
I believe everything will be accounted for if you move the new attempt with `-lpthread` to the `else` case currently on line 470 (in this PR), and do it before falling back to the current call to `detect` that is there.

**Comment by oandrieu** [comment]
Ah yes thanks, indeed I suspected that `pthread` had a special status on some platforms.

**Comment by aantron** [comment]
Thanks! And sorry about the delay on the original issue; I was away and only am now draining the backlog.

**Pull request merged**
