### PR TITLE
Lwt_preemptive: work around Event.sync perf issue.

### LINKED ISSUE #218: Lwt_preemptive.detach forces a full major GC run every 2500 calls at most
`Lwt_preemptive` uses `Event` channels which under the hood allocate one condition variable per `Event.sync`. The parameters given to `caml_alloc_custom` when creating the condition variable indicate that at most 5000 values can be left unreclaimed. Heavy GC load ensues. 

See https://github.com/mfp/ocaml-sqlexpr/issues/13

Also, should a (performance) bug be filed against OCaml's `Event` module?

### PR DESCRIPTION
**Pull request by mfp**
Refer to

   http://caml.inria.fr/mantis/view.php?id=7158
   https://github.com/ocsigen/lwt/issues/218.
   https://github.com/mfp/ocaml-sqlexpr/issues/13

Fix #218.

### CODE REVIEW

**Comment by mfp** [comment]
Extra eyeballs appreciated, it's very late over here :-/

**Comment by aantron** [comment]
@mfp: Do you have some idea, from your discussions and experience, what the impact of resolving the two Mantis issues ([1](http://caml.inria.fr/mantis/view.php?id=7158), [2](http://caml.inria.fr/mantis/view.php?id=7198)) will be? As in, is there a nice way to resolve them, such that `Event` creating all those `Condition.t`s won't be a performance issue anymore?

If performance will still be a problem, we should definitely merge this. If it won't be a problem anymore, we can still merge this, but I'm only about 75% convinced in that case – because it's a vanishing problem given the target of 4.03.1, and because it adds code. In that case, further arguments are welcome :)

**Comment by aantron** [comment]
cc @hcarty since he is working on a [potential replacement or alternative](https://github.com/hcarty/mwt) to `Lwt_preemptive`.

@hcarty: would be interested about your experience/opinion on `Mwt` or `Lwt_preemptive` being subjected to the kind of usage that causes problems here.

**Comment by hcarty** [comment]
I haven't run into this largely because the cases where I've used `Lwt_preemptive` have been for heavier calls. So some extra GC overhead would be lost in the noise.

That is likely to change soon though so I would be happy to see performance improvements here! My main question is if this should live in Lwt or as a separate module/library in opam, used by Lwt.

**Comment by mfp** [comment]
On Tue, Jun 21, 2016 at 04:59:08PM -0700, Anton wrote:
> @mfp: Do you have some idea, from your discussions and experience, what the impact of resolving the two Mantis issues ([1](http://caml.inria.fr/mantis/view.php?id=7158), [2](http://caml.inria.fr/mantis/view.php?id=7198)) will be? As in, is there a nice way to resolve them, such that `Event` creating all those `Condition.t`s won't be a performance issue anymore?
> 
> If performance will still be a problem, we should definitely merge this. If it won't be a problem anymore, we can still merge this, but I'm only about 75% convinced in that case – because it's a vanishing problem given the target of 4.03.1, and because it adds code. In that case, further arguments are welcome :)

The moment these issues are resolved, this PR will become unnecessary.
However, I'm not sure MPR7158 can be readily solved in a direct way (TBH, I
haven't made any serious attempt to understand that code, which is at any rate
much trickier than the present PR), and addressing MPR7198 would require work
on the GC and/or a new API, which could take a long time to happen (regardless
of the target version... I'm not sure it means it *will* positively be fixed
by that time).

Note that this PR addresses the performance issue as far as `detach` is
concerned, but `run_in_main` will still be affected (this could be solved
easily by pooling the mutexes/conditions or cells, at the cost of some more
code).

I'd say there are two arguments for merging this, and one and a half against:

pros:

* merging this solves the `detach` issue *now*
* and *for all OCaml versions*

cons:

* I might have introduced a bug (the code looks easy to inspect to me, though)
* this adds code, but given Lwt_preemptive's history (no significant changes
  in the last 4 years), it would be easy to revert at a later point in time if
  the MPRs are addressed directly and older OCaml targets become irrelevant

-- 
Mauricio Fernández

**Comment by mfp** [comment]
On Fri, Jul 01, 2016 at 06:39:53PM -0700, Hezekiah M. Carty wrote:
> I haven't run into this largely because the cases where I've used `Lwt_preemptive` have been for heavier calls. So some extra GC overhead would be lost in the noise.
> 
> That is likely to change soon though so I would be happy to see performance improvements here! My main question is if this should live in Lwt or as a separate module/library in opam, used by Lwt.

The fix is specific to Lwt_preemptive's use of Event -- it does not solve the
overall Event/GC issue. The "cell" implementation is small enough to live
comfortably in Lwt_preemptive and avoid both the extra work to release it as a
separate OPAM package and adding a new dependency to Lwt.

-- 
Mauricio Fernández

**Comment by aantron** [comment]
Ok, I am convinced :)

> My main question is if this should live in Lwt or as a separate module/library in opam, used by Lwt.

Assuming you mean module `CELL`, I don't think it's worth it at this point – this is just a regular data structure + CV + mutex. Plus, I don't think stdlib threads are used that much.

<br/>

The change is not so trivial actually, because it replaces a queue (channel) with a single cell (the mutable option), but it appears to be correct.

Rebased on master, committed.

> but `run_in_main` will still be affected

I'm adding a comment, in a [follow-on commit](b6aa378ef0cb4e112a621a1002c81b184f16980f), about the potential performance issue, above the implementation of `run_in_main`, so that if someone is ever debugging that, they might be able to save some time by quickly finding this PR and #218.

Thank you!

**Pull request closed without merging**
