### PR TITLE
Move lwt_glib to its own repository

### PR DESCRIPTION
**Pull request by aantron**
It can now be found at [aantron/lwt_glib](https://github.com/aantron/lwt_glib), where it has its own build system and CI setup. I've `filter-branch`ed the entire history of `lwt_glib` out into that repo.

This breaks the "unified" docs build of Lwt, but that has been broken since mid-2017 at this point anyway. The Ocsigen infrastructure seems to be down.

I don't know if we need a new opam release of `lwt_glib`. The only significant change is the `dev-repo` field should now point to the other repo.

I built `lwt_glib` from that repo, and built `0install`, its only opam dep, against it. It seems to work fine.

After this point, we can treat `lwt_glib` as another ordinary user of Lwt. This simplifies CI and avoids wasting the attention of contributors.

Part of #511.

cc @talex5

### CODE REVIEW

**Comment by hannesm** [comment]
@aantron you mentioned that the only change for a release would be a `dev-repo` update -- you can do this directly in the opam file in opam-repository.  though the `url` will still point to the latest `lwt` tarball, but i guess that's fine..

**Comment by aantron** [comment]
Thanks @hannesm. That shouldn't cause people to re-download `lwt_glib` and trigger re-building of deps, right? I'm assuming that would only be triggered by changing the `url` file, specifically the checksum (which indeed doesn't have to change).

**Comment by Drup** [comment]
Do you want me to move the repository inside ocsigen's organization ?

**Comment by aantron** [comment]
> Do you want me to move the repository inside ocsigen's organization ?

I believe @Drup has continued this discussion here: https://github.com/ocsigen/lwt/issues/511#issuecomment-354983413

**Pull request merged**
