### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by Drup**
Should fix https://github.com/ocsigen/lwt/issues/209
cc @fxfactorial

For the oasis part of the question, I oppened https://github.com/ocaml/ocamlbuild/issues/45

### CODE REVIEW

**Comment by aantron** [comment]
You might even want to contrast `>>` with `>>=`, since this is what is setting up the expectation in the first place. `Note that unlike [>>=], [>>] is not an OCaml value`..., or something.

**Comment by Drup** [comment]
@aantron They are recorded, but it's going to be so mangled it might as well not be the case. I added a slight precision. I also added more pointers to the manual.
Your formulation for `>>` is better, thanks!

**Comment by aantron** [comment]
Strange, why aren't there links to comments on outdated diffs?

**Comment by aantron** [comment]
Looks good, apart from the semicolon in the message for https://github.com/ocsigen/lwt/commit/533ef6f89cad7639bf9fd4f575ccb3ae30201af8 :)

**Pull request merged**
