### PR TITLE
Nix

### PR DESCRIPTION
**Pull request by dmjio**
Add a nix build for `lwt` locally.

#### Usage

```bash
$ nix-build
```

#### Result
```
λ Davids-MacBook-Pro lwt → λ git nix* → nix-build
these derivations will be built:
  /nix/store/cn14qgvq7j5ml4whjfzjmxim4zf904nq-ocaml4.09.1-lwt-0.5.0.drv
building '/nix/store/cn14qgvq7j5ml4whjfzjmxim4zf904nq-ocaml4.09.1-lwt-0.5.0.drv'...
unpacking sources
unpacking source archive /nix/store/9jw1mviscg75gm06v1rwysjsanwny3i4-lwt
source root is lwt
patching sources
configuring
no configure script, doing nothing
building
installing
post-installation fixup
moving /nix/store/lc04pc9x6g9kl1hr745zrxz1gm9xr9s0-ocaml4.09.1-lwt-0.5.0/doc to /nix/store/lc04pc9x6g9kl1hr745zrxz1gm9xr9s0-ocaml4.09.1-lwt-0.5.0/share/doc
strip is /nix/store/j6148qvjhcm25yqh852mcc3rv4wfpdwy-cctools-binutils-darwin-927.0.2/bin/strip
stripping (with command strip and flags -S) in /nix/store/lc04pc9x6g9kl1hr745zrxz1gm9xr9s0-ocaml4.09.1-lwt-0.5.0/lib 
patching script interpreter paths in /nix/store/lc04pc9x6g9kl1hr745zrxz1gm9xr9s0-ocaml4.09.1-lwt-0.5.0
/nix/store/lc04pc9x6g9kl1hr745zrxz1gm9xr9s0-ocaml4.09.1-lwt-0.5.0
```

### CODE REVIEW

**Comment by dmjio** [comment]
Still attempting to figure out why tests don't build on darwin.

```
these derivations will be built:
  /nix/store/89pc3m0pn7f2qcl97a0d3j8sq80syh6r-ocaml4.09.1-lwt-0.5.0.drv
building '/nix/store/89pc3m0pn7f2qcl97a0d3j8sq80syh6r-ocaml4.09.1-lwt-0.5.0.drv'...
unpacking sources
unpacking source archive /nix/store/hvgcr6j650zclljwncqzd0bz1s41s3i9-lwt
source root is lwt
patching sources
configuring
no configure script, doing nothing
building
running tests
File "test/dune", line 4, characters 21-29:
4 |  (libraries lwt unix lwt.unix))
                         ^^^^^^^^
Error: Library "lwt.unix" in _build/default/src/unix is hidden (optional with
unavailable dependencies).
Hint: try: dune external-lib-deps --missing -p lwt @runtest
```

**Comment by aantron** [comment]
> Still attempting to figure out why tests don't build on darwin.

The most immediate answer is that one of these ocamlfind packages is missing:

https://github.com/ocsigen/lwt/blob/6cb8a5a32ba1398e097c788837d4c4d64c371d52/src/unix/dune#L45

In opam, these come from packages...

- `base-bigarray`, `base-unix`, `ocaml` which are installed with the compiler,
- [`mmap`](https://github.com/mirage/mmap) and [`ocplib-endian`](https://github.com/OCamlPro/ocplib-endian), which are third-party packages.

It's more than the tests which aren't building, but `lwt.unix`, which is the OS binding of Lwt.

**Comment by dmjio** [comment]
Added `mmap` and `ocplib-bigendian`, tests now pass on Darwin.

```
running tests
        main alias test/core/runtest
Testing library 'core'...
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SSSSSSSSSSSSSSSSSSSSSSS...............................................................................................................
Ok. 637 tests ran, 23 tests skipped in 0.01 seconds
        main alias test/unix/runtest
Testing library 'unix'...
.................................SSS...................................................................................................................................................................................
Ok. 212 tests ran, 3 tests skipped in 6.32 seconds
installing
post-installation fixup
```

**Comment by aantron** [comment]
I think this should be maintained in nixpkgs at https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/ocaml-modules/lwt.

**Pull request closed without merging**
