### PR TITLE
utf8ize names in comments

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by vbmithr** [comment]
Why did you delete "Paris" in "Université Paris Diderot" most of the times ? Had a bad experience in Paris, huh ? :)

**Comment by rgrinberg** [comment]
Oops. Paris is back :)

**Comment by Drup** [comment]
nope, not all of them.

**Comment by rgrinberg** [comment]
OK, fixed. Forgot to stage everything...

**Pull request merged**
