### PR TITLE
lwt_ppx: carry explicit dependency from dune to opam

### PR DESCRIPTION
**Pull request by raphael-proust**
Thanks `opam-dune-lint` for the fix

### CODE REVIEW

**Comment by aantron** [comment]
Does the code of lwt_ppx itself have this exact constraint on ocaml-compiler-libs? I assume we do directly use ocaml-compiler-libs.

**Comment by raphael-proust** [comment]
The file `src/ppx/dune` lists `ocaml-compiler-libs.common` as a dependency.

I removed the dependency and it still builds. It seems the recent port to ppxlib actually removed the direct use of this library.

I've just pushed a version with the dependency removed from the dune file.

**Comment by aantron** [comment]
It might still be pulled in transitively by ppxlib. Does the code of the PPX use any module from `ocaml-compiler-libs.common`? If so, it should be listed in both `dune` and `opam`, and the constraint in `opam` should be set according to what the code in the PPX requires.

**Comment by avsm** [comment]
Fixed in #838

**Pull request closed without merging**
