### PR TITLE
Depessimize lwt ssl

### PR DESCRIPTION
**Pull request by mfp**
Addresses #98.

### CODE REVIEW

**Comment by mfp** [comment]
The builder reports a failure because it uses ssl 0.4.7, and the functions this PR builds upon were added in the recently released 0.5.0.

Note that Ssl.read_into_bigarray & friends have not been tested (but [they've been reviewed](https://github.com/savonet/ocaml-ssl/pull/15#issuecomment-65264830)).

I think that it should be safe to use `Ssl.read_into_array_blocking` and `Ssl.write_into_array_blocking`, because Lwt_ssl should be operating with non-blocking sockets. I've however used the variants that release the runtime to keep it safe. If nobody sees a reason not to do it, the code can be changed trivially to the slightly faster variants.

**Comment by Drup** [comment]
If you rely on a specific version of ssl, please add a constraint in the opam file.

**Comment by mfp** [comment]
Added to opam. Note that the ssl 0.5.0 PR for the OPAM repository is yet to be merged https://github.com/ocaml/opam-repository/pull/4132

**Comment by vbmithr** [comment]
@drup could you give it a spin of CI ? If not, I'll check manually.

**Comment by mfp** [comment]
On Thu, Jul 02, 2015 at 08:36:29AM -0700, Vincent Bernardoff wrote:
> @drup could you give it a spin of CI ? If not, I'll check manually.

FWIW, it "builds for me", and I just gave it a quick test with this:

    (* invoke as   ./t www.facebook.com   *) 
    (* ocamlfind ocamlopt -package lwt.ssl -o t t.ml -linkpkg *)

    open Lwt

    let request = "GET / HTTP/1.0\r\n\r\n"

    let run () =
      Ssl.init ();
      let addr = match
                   Unix.getaddrinfo Sys.argv.(1) "443"
                     [Unix.AI_FAMILY Unix.PF_INET; Unix.AI_PROTOCOL 6]
                 with
                   | [] -> failwith "can't resolve"
                   | { Unix.ai_addr; _ } :: _ -> ai_addr in
      let c    = Ssl.create_context Ssl.SSLv23 Ssl.Client_context in
      let sock = Lwt_unix.socket Unix.PF_INET Unix.SOCK_STREAM 0 in
        Lwt_unix.connect sock addr >>= fun () ->
        Lwt_ssl.ssl_connect sock c >>= fun ssl ->
        let ich = Lwt_ssl.in_channel_of_descr ssl in
        let och = Lwt_ssl.out_channel_of_descr ssl in
        Lwt_io.write och request >>= fun () ->
        Lwt_io.flush och >>= fun () ->
        Lwt_io.read ich >|= print_endline

    let () = Lwt_main.run (run ())


Note that running it against e.g.  www.google.com  results in a

    Ssl.Read_error Ssl.Error_syscall

exception because the other end does not perform a proper TLS shutdown. I
have verified this happens also without this PR. This probably deserves a
separate bug report, but I'm not sure where (probably ocaml-ssl, sigh).

-- 
Mauricio Fernández

**Pull request merged**
