### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### ocsigen/lwt now has a Chat Room on Gitter

@aantron has just created a chat room. You can visit it here: [https://gitter.im/ocaml-lwt/Lobby](https://gitter.im/ocaml-lwt/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/ocaml-lwt/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by dannywillems** [comment]
Oh it's interesting! It must be the same for all other ocsigen projects I think.

**Comment by aantron** [comment]
I'm 95% sure I asked Gitter not to submit this annoying PR. Oh well, I guess it's a good way to let people know about it :)

**Comment by rgrinberg** [comment]
@aantron why? I think it would be nice to include a link to the gitter in the README. Otherwise it's a bit hard to discover.

**Comment by aantron** [comment]
Oh yeah, I'm adding a badge in a new `README`, I just didn't want it by this PR :)

**Pull request closed without merging**
