### PR TITLE
Fix compilation with musl-gcc

### LINKED ISSUE #718: Lwt 4.3 breaks compilation with musl
To reproduce:

```
% opam switch create 4.09.0+musl+flambda
% cat test.ml
let () = Lwt_main.run (Lwt.return ())
% cat dune
(executable (name test) (libraries lwt lwt.unix))
% dune build test.exe
    ocamlopt test.exe (exit 2)
(cd _build/default && ~/.opam/4.09.0+musl+flambda/bin/ocamlopt.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -o test.exe -I ~/.opam/4.09.0+musl+flambda/lib/bytes -I ~/.opam/4.09.0+musl+flambda/lib/lwt -I ~/.opam/4.09.0+musl+flambda/lib/lwt/unix -I ~/.opam/4.09.0+musl+flambda/lib/mmap -I ~/.opam/4.09.0+musl+flambda/lib/ocaml/threads -I ~/.opam/4.09.0+musl+flambda/lib/ocplib-endian -I ~/.opam/4.09.0+musl+flambda/lib/result -I ~/.opam/4.09.0+musl+flambda/lib/seq ~/.opam/4.09.0+musl+flambda/lib/result/result.cmxa ~/.opam/4.09.0+musl+flambda/lib/lwt/lwt.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocaml/unix.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocaml/bigarray.cmxa ~/.opam/4.09.0+musl+flambda/lib/mmap/mmap.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocplib-endian/bigstring.cmxa ~/.opam/4.09.0+musl+flambda/lib/ocaml/threads/threads.cmxa ~/.opam/4.09.0+musl+flambda/lib/lwt/unix/lwt_unix.cmxa .test.eobjs/native/test.cmx)
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libthreadsnat.a(st_stubs_n.o): in function `caml_thread_start':
st_stubs.c:(.text+0xab1): undefined reference to `sigsetjmp'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(startup_nat_n.o): in function `caml_startup_common':
~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/startup_nat.c:156: undefined reference to `sigsetjmp'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_secure_getenv':
~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:418: undefined reference to `issetugid'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlopen':~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:278: undefined reference to `dlopen'/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlclose':~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:284: undefined reference to `dlclose'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlsym':
~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:289: undefined reference to `dlsym'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:289: undefined reference to `dlsym'
/opt/x86_64-linux-musl-native/bin/../lib/gcc/x86_64-linux-musl/9.1.0/../../../../x86_64-linux-musl/bin/ld: ~/.opam/4.09.0+musl+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_dlerror':~/.opam/4.09.0+musl+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+flambda/runtime/unix.c:303: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:Error: Error during linking
```

Looks like `lwt_unix.cmxa` adds `/usr/lib` to the search path:

```
% ocamlobjinfo ~/.opam/4.09.0+musl+flambda/lib/lwt/unix/lwt_unix.cmxa|grep object
Extra C object files: -llwt_unix_stubs -L/usr/lib -lpthread
```

In 4.2.1 it works fine:

```
% opam install lwt=4.2.1
The following actions will be performed:
⊘ removed   lwt.4.3.0
∗ installed lwt.4.2.1
Done.
% dune build test.exe
% ocamlobjinfo ~/.opam/4.09.0+musl+flambda/lib/lwt/unix/lwt_unix.cmxa|grep object
Extra C object files: -llwt_unix_stubs -lpthread 
```

This switch uses musl-gcc, which uses its own search path. It isn't compatible with objects from `/usr/lib` which were compiled with glibc. 

<hr>

Relatedly, when installing conf-libev, I need to pass `C_INCLUDE_PATH` and `LIBRARY_PATH` even though my compiler already has the right search paths baked in:

```
% cat test.c
#include <ev.h>
int main() {}
% musl-gcc test.c -lev
```

### PR DESCRIPTION
**Pull request by aantron**
- [x] Don't add unnecessary flags: rely on `musl-gcc`'s search paths.
- [x] Fix libev search.
- [x] Build with musl in one of the Travis rows to avoid regression.

Fixes #718.

cc @copy

### CODE REVIEW

**Comment by aantron** [comment]
@copy, for setting this up in Travis, can you say how you are installing a musl libev (unless you are on a musl system)? The way I see now is to cross-compile from source, and manually install to `/usr/*/x86_64-linux-musl`.

**Comment by aantron** [comment]
There is a potential compiler bug with float literals on musl: https://github.com/ocaml/ocaml/issues/8977.

**Comment by copy** [comment]
> for setting this up in Travis, can you say how you are installing a musl libev (unless you are on a musl system)? The way I see now is to cross-compile from source, and manually install to /usr/*/x86_64-linux-musl.

Exactly like you did in this PR, except in my case I use a pre-compiled toolchain from https://musl.cc/ which I copy into `/opt/x86_64-linux-musl-native` and then compile libev using `CC=/opt/x86_64-linux-musl-native/bin/gcc ./configure --prefix=/opt/x86_64-linux-musl-native`.

> There is a potential compiler bug with float literals on musl: ocaml/ocaml#8977.

Heh, nice find!

**Comment by aantron** [comment]
The "compiler" bug is actually a musl bug, my report just passed moderation here: https://www.openwall.com/lists/musl/2019/09/25/10. It's still present in musl `master`.

@copy, I think this PR takes care of the needed changes in the Lwt repo, and there is now a Travis row for building with musl and libev, which you saw: https://travis-ci.org/ocsigen/lwt/jobs/589473537

Can you confirm that this branch, `musl`, fixes the Lwt install for you? Then, I will merge this PR.

I'm still debugging `conf-libev`, the problem right now is that it *appears* to be working for me, but I expect to be able to break it shortly :)

**Comment by copy** [comment]
> Can you confirm that this branch, musl, fixes the Lwt install for you?

Yes, cheers.

**Pull request merged**
