### PR TITLE
Reorg lwt unix c files part 2

### LINKED ISSUE #407: [easy-ish] Reorganize the C files
Lwt's C files are currently quite messy. For example, [`lwt_unix_unix.h`](https://github.com/ocsigen/lwt/blob/6649ef6f74fdff417e705e131e5ec31487ea9032/src/unix/lwt_unix_unix.h) is currently about 3300 lines of stress-inducing C code, which is enough to give anyone a headache. Also, it shouldn't be a header file – everything in it is an implementation. However, it is [currently included from `lwt_unix_stubs.c` as a janky form of conditional compilation](https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_unix_stubs.c#L90-L94).

Fixing that conditional compilation scheme might be somewhat involved, but the first thing we should do is split up `lwt_unix_unix.h` and `lwt_unix_windows.h` into lots of little files, close to one per C call or small C call category. For comparison, see the files of [`Unix` from the standard library](https://github.com/ocaml/ocaml/tree/50b2c095e6772e4a058434d328d59b7094a4dbff/otherlibs/unix), and the [Windows equivalent](https://github.com/ocaml/ocaml/tree/50b2c095e6772e4a058434d328d59b7094a4dbff/otherlibs/win32unix).

We can create all those little files in two new subdirectories of [`src/unix/`](https://github.com/ocsigen/lwt/tree/6649ef6f74fdff417e705e131e5ec31487ea9032/src/unix) (one for actual Unix and one for Windows), and, as a first cut, `#include` each one of them into either `lwt_unix_unix.h` and `lwt_unix_windows.h`. This should be relatively simple, as C preprocessor inclusion is textual substitution. Header guards (`#pragma once` or `#ifndef`) are not necessary, because we know each of these files is only going to be included once, and also because the ultimate plan is to turn them into `.c` files eventually.

It would be great if we could figure out how to make git trace the history of each one of these files back to `lwt_unix_unix.h` or `lwt_unix_windows.h`, but I doubt git is actually able to do that.

**If you'd like to work on this, please leave a comment below. We want to make sure that nobody else is likely modifying these files at the same time, to avoid a potentially brutal merge conflict.**

### PR DESCRIPTION
**Pull request by cedlemo**
EDIT by @aantron: resolves #407.

### CODE REVIEW

**Comment by aantron** [comment]
Looking pretty good. I still see a few errors:

```
      ocamlc src/unix/unix_get_pw_gr_nam_id_job.o
unix_get_pw_gr_nam_id_job.c:133:15: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
JOB_GET_ENTRY(LWT_UNIX_INIT_JOB_STRING(job, getpwnam, 0, name), getpwnam, GETPW,
              ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_get_pw_gr_nam_id_job.c:133:15: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_getcwd_job.o
      ocamlc src/unix/unix_getaddrinfo_job.o
      ocamlc src/unix/unix_gethostbyaddr_job.o
      ocamlc src/unix/unix_gethostbyname_job.o
      ocamlc src/unix/unix_getlogin_job.o
      ocamlc src/unix/unix_gethostname_job.o
      ocamlc src/unix/unix_getnameinfo_job.o
      ocamlc src/unix/unix_invalidate_dir.o
      ocamlc src/unix/unix_guess_blocking_job.o
      ocamlc src/unix/unix_getprotoby_getservby_job.o
unix_getprotoby_getservby_job.c:249:16: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
JOB_GET_ENTRY2(LWT_UNIX_INIT_JOB_STRING(job, getprotobyname, 0, name),
               ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_getprotoby_getservby_job.c:249:16: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_iov_max.o
      ocamlc src/unix/unix_isatty_job.o
      ocamlc src/unix/unix_lockf_job.o
      ocamlc src/unix/unix_lstat_64_job.o
unix_lstat_64_job.c:36:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, lstat, 0, name);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_lstat_64_job.c:36:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_lstat_job.o
unix_lstat_job.c:36:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, lstat, 0, name);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_lstat_job.c:36:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_madvise.o
      ocamlc src/unix/unix_mcast_modify_membership.o
unix_mcast_modify_membership.c:60:13: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
            memcpy(&mreq.imr_multiaddr, &GET_INET_ADDR(group_addr), 4);
            ^
unix_mcast_modify_membership.c:60:13: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 warning generated.
      ocamlc src/unix/unix_mcast_set_loop.o
      ocamlc src/unix/unix_mcast_set_ttl.o
      ocamlc src/unix/unix_mcast_utils.o
      ocamlc src/unix/unix_not_available.o
      ocamlc src/unix/unix_open_job.o
unix_open_job.c:132:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, open, 0, name);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_open_job.c:132:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_mincore.o
      ocamlc src/unix/unix_opendir_job.o
unix_opendir_job.c:62:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, opendir, 0, path);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_opendir_job.c:62:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_read.o
      ocamlc src/unix/unix_readable.o
      ocamlc src/unix/unix_read_job.o
unix_read_job.c:69:9: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
        memcpy(String_val(job->string) + job->offset, job->buffer, result);
        ^
unix_read_job.c:69:9: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 warning generated.
      ocamlc src/unix/unix_readdir_job.o
      ocamlc src/unix/unix_readdir_n_job.o
unix_readdir_n_job.c:71:22: warning: implicitly declaring library function 'strdup' with type 'char *(const char *)' [-Wimplicit-function-declaration]
        char *name = strdup(entry->d_name);
                     ^
unix_readdir_n_job.c:71:22: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
1 warning generated.
      ocamlc src/unix/unix_readv.o
      ocamlc src/unix/unix_readlink_job.o
unix_readlink_job.c:81:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, readlink, 0, name);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_readlink_job.c:81:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_readv_job.o
unix_readv_job.c:66:13: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
            memcpy(&Byte(String_val(read_buffer->caml_buffer),
            ^
unix_readv_job.c:66:13: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 warning generated.
      ocamlc src/unix/unix_readv_writev_utils.o
unix_readv_writev_utils.c:60:17: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
                memcpy(buffer_copies[copy_index],
                ^
unix_readv_writev_utils.c:60:17: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 warning generated.
      ocamlc src/unix/unix_recv_msg.o
      ocamlc src/unix/unix_recv.o
      ocamlc src/unix/unix_recvfrom.o
      ocamlc src/unix/unix_recv_send_utils.o
unix_recv_send_utils.c:71:5: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    memset(&msg, 0, sizeof(msg));
    ^
unix_recv_send_utils.c:71:5: note: include the header <string.h> or explicitly provide a declaration for 'memset'
1 warning generated.
      ocamlc src/unix/unix_rewinddir_job.o
      ocamlc src/unix/unix_send.o
      ocamlc src/unix/unix_sendto_byte.o
      ocamlc src/unix/unix_send_msg.o
      ocamlc src/unix/unix_sendto.o
      ocamlc src/unix/unix_set_affinity.o
      ocamlc src/unix/unix_stat64_job.o
unix_stat64_job.c:36:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, stat, 0, name);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_stat64_job.c:36:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_stat_job.o
unix_stat_job.c:36:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, stat, 0, name);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_stat_job.c:36:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_tcgetattr_job.o
      ocamlc src/unix/unix_stat_job_utils.o
      ocamlc src/unix/unix_tcsetattr_job.o
unix_tcsetattr_job.c:73:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    memcpy(&job->termios, &Field(termios, 0), NFIELDS * sizeof(value));
    ^
unix_tcsetattr_job.c:73:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 warning generated.
      ocamlc src/unix/unix_utimes_job.o
unix_utimes_job.c:61:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    LWT_UNIX_INIT_JOB_STRING(job, utimes, 0, path);
    ^
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
unix_utimes_job.c:61:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
./lwt_unix.h:272:5: note: expanded from macro 'LWT_UNIX_INIT_JOB_STRING'
    memcpy(VAR->ARG, String_val(ARG), __len + 1)
    ^
1 warning generated.
      ocamlc src/unix/unix_termios_conversion.o
      ocamlc src/unix/unix_valid_dir.o
      ocamlc src/unix/unix_wait4.o
      ocamlc src/unix/unix_writable.o
      ocamlc src/unix/unix_wait_mincore_job.o
unix_wait_mincore_job.c:46:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    memcpy(&dummy, job->ptr, 1);
    ^
unix_wait_mincore_job.c:46:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 warning generated.
      ocamlc src/unix/unix_write.o
      ocamlc src/unix/windows_bytes_read.o
      ocamlc src/unix/unix_write_job.o
unix_write_job.c:64:5: warning: implicitly declaring library function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Wimplicit-function-declaration]
    memcpy(job->buffer, String_val(val_string) + Long_val(val_offset), length);
    ^
unix_write_job.c:64:5: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 warning generated.
```

This is due to some different headers on macOS from Linux. You can also see these errors here: https://travis-ci.org/ocsigen/lwt/jobs/320786768#L1651.

Since I have to review this commit-by-commit anyway, though (thanks for breaking it up that way, I like this history :)), I propose that I just go through the PR, and rebuild its history, fixing those little errors along the way in whatever commit introduced them. It will help me be thorough in the review.

Otherwise, if you'd like to fix it yourself, please go ahead, and let me know when it's ready for the review :)

**Comment by cedlemo** [comment]
> Otherwise, if you'd like to fix it yourself, please go ahead, and let me know when it's ready for the review 

Yes please.

**Comment by aantron** [comment]
Thanks for doing this! Looking back on it, some of the files may be a bit too fine-grained, but we can fix that later as we go, and it's *much* better than what we had before the PR. Probably the next step in the Unix binding cleanup is to un-develop the stubs generator, `src/unix/stubs`. It generates the code for most of the more repetitive system call bindings. It's pretty opaque, and therefore difficult to maintain.

**Comment by cedlemo** [comment]
> Thanks for doing this! Looking back on it, some of the files may be a bit too fine-grained, but we can fix that later as we go

tell me if I can help.

> un-develop

I don't understand this word, could explain it to me ?

**Pull request merged**
