### PR TITLE
Prepare for release

### PR DESCRIPTION
**Pull request by raphael-proust**
Version 5.7.0

Don't merge for now

### CODE REVIEW

**Comment by MisterDA** [comment]
Can you consider merging #967 before cutting the release?

**Comment by MisterDA** [comment]
There were a few comments from February on the ocamllabs slack channel suggesting the code snippet was small enough to be merged. 
If you're still worried about license considerations, I strongly suggest you merge the related code we know won't be affected, like the failing test. You might then get someone without knowledge of the code snippet (a willing intern? a dedicated hackers' grandmother?) to write a clean-room implementation of it, without looking at the source of the stdlib, with the help of the test. But I'm not a lawyer.

**Comment by samwgoldman** [comment]
Now that 5.1.0~rc1 is released, I'd like to give it a try, but we currently can't test because of our dependency on Lwt. Looking forward to a release with compatibility with OCaml 5.1. Thank you!

**Comment by raphael-proust** [comment]
> Now that 5.1.0~rc1 is released, I'd like to give it a try, but we currently can't test because of our dependency on Lwt. Looking forward to a release with compatibility with OCaml 5.1. Thank you!

The release should be merged soon. The PR for it is https://github.com/ocaml/opam-repository/pull/24213

**Pull request merged**
