### PR TITLE
Add support for ppx_let

### PR DESCRIPTION
**Pull request by brendanlong**
See #667

### CODE REVIEW

**Comment by hcarty** [comment]
Could this be put in a separate module, something like `Lwt.Ppx_let`?  That way the infix operators aren't pulled into scope along with the `Let_syntax` module.

**Comment by aantron** [comment]
I'm also not sure about where this should go. A separate module seems reasonable, since, presumably, the two preferences, using infix operators, and using ppx_let, are mutually exclusive.

@brendanlong I suggest omitting `Lwt.both`, and only defining it in the `Let_syntax` module.

**Comment by brendanlong** [comment]
>  presumably, the two preferences, using infix operators, and using ppx_let, are mutually exclusive.

It's very common to mix them since point-free coding style is still useful (for the same reason `|>` is common in code that also uses `let`), so I suspect almost every user of ppx_let will also want the infix operators in scope. For what it's worth, Jane Street libraries put `Let_syntax` inside of the `Monad_infix` modules.

You can see examples of this in [sentry-ocaml](https://github.com/brendanlong/sentry-ocaml/blob/master/src/client.ml#L54) and [mssql](https://github.com/arenadotio/ocaml-mssql/blob/master/src/client.ml#L249) (even using `>>|` inside of `let%map`).

That said, it's also true that people opening `Lwt.Infix` who don't use ppx_let won't necessarily want `Let_syntax` in scope. I'm not sure what the downside of this is but I can move it if you want.

I can also move `both` although it seems strange to have it and only expose it in the ppx_let bindings. I couldn't really follow the implementation of `Lwt.join`, so I'm also wondering if I implemented `both` correctly or if I should have done something different?

**Comment by aantron** [comment]
Ok, then let's leave it in `Lwt.Infix`.

The issue with `Lwt.both` is its rejection semantics. The implementation favors the `'a t`: as soon as it is rejected, the state (or fate) of the `'b t` doesn't matter, even if it was rejected first, or is still pending. Once the `'a t` is rejected, first or last, the rejection is immediately propagated to the `('a * 'b) t`. However, if the `'b t` is rejected first, this `Lwt.both` continues to "wait" for the `'a t`, potentially forever.

These asymmetric semantics might make sense if `Lwt.both` is only bound under `Lwt.Infix.Let_syntax.both`, and is therefore mostly hidden behind `and` syntax, because in that case, at least the `let` promise arises first syntactically, and we can imagine that there is some kind of evaluation order issue.

But, for an explicit `Lwt.both`, with such a type signature, I would expect the semantics to be symmetric, that is, in some sense, commutative. These two pieces of code:

```
Lwt.on_failure (Lwt.both a b) f
Lwt.on_failure (Lwt.both b a) f
```

should be equivalent.

If you'd like to add `Lwt.both` to `Lwt`, I think the easiest way is to take advantage of the existing `Lwt.join`, and use `Result.result ref`s to store values/exceptions.

Alternatively, I can merge a version of this PR with only `Lwt.Infix.Let_syntax.both`.

Or, please discuss :)

**Comment by aantron** [comment]
See also #325, "More general join and choose operators."

**Comment by brendanlong** [comment]
Hm yeah maybe it makes sense to implement `Lwt.both` in terms of `Lwt.join` for now, and then optimize it later if someone has time (to ensure that we don't get stuck maintaining a weird implementation for backwards compatibility). Do you think it makes sense to add that as `Lwt.both` or should it stay in `Lwt.Infix.Let_syntax.both` for now?

**Comment by aantron** [comment]
An `Lwt.both` implemented in terms of `Lwt.join` (thus with its semantics) would be a welcome addition to the main module, `Lwt` :) There might be some trickiness with cancelation semantics (another Lwt annoyance :/), but there is a high chance of getting them right, and if anything is wrong, I can comment and give options on how to adjust the implementation.

**Comment by aantron** [comment]
@brendanlong I'd like to release Lwt 4.2.0 soon (#675), with this PR included. Would you mind if I took over and added the new `Lwt.both`? Or, you are very welcome if you have the time to do it :)

**Comment by brendanlong** [comment]
@aantron That would be fine to me. Sorry, I wanted to make a better version of `both` but haven't had time to look into this much again. If you want to do it that would be great!

**Comment by aantron** [comment]
@brendanlong I replaced (most of) the first commit (adding `Lwt.both`) by a different implementation, then cherry-picked your docs and `Let_syntax` module, and added some new tests (spread over the commits). Thanks!

I should note that the `Lwt.both` in the new first commit is structurally identical to `<&>` proposed by @yallop in #325.

**Pull request merged**
