### PR TITLE
removed the unnecessary "ugly cast" from function add_cancel_callback

### PR DESCRIPTION
**Pull request by esope**
Removed an unnecessary Obj.magic

### CODE REVIEW

**Comment by raphael-proust** [comment]
I pushed a commit, but it's more of a suggestion. The idea is to use the named type alias (`cancel_callback`) instead of the expanded definition (`unit -> unit`) in places where it is used. This is sort of complementary to the removal of the cast so I pushed it here.

If you prefer, I'll push it in its own branch and merge it through there.

**Comment by esope** [comment]
This change is a good idea, indeed. Thanks. Makes things clearer. No need to add this change somewhere else and then merge it.

**Comment by raphael-proust** [comment]
@esope I'll rebase this branch on master so that it goes through the newer CI system that landed there. I'll mere it once it passes that CI.

**Comment by raphael-proust** [comment]
I rebased on master and resolved the conflict (which was only in the changelog)

**Pull request merged**
