### PR TITLE
Lwt_list: More tests.

### PR DESCRIPTION
**Pull request by ryanslade**
Also formatted the code using ocp-indent and renamed the tests so they
have descriptive names instead of just numbers.

### CODE REVIEW

**Comment by ryanslade** [comment]
One other thing, can we translate the comment in test_exception into English?

**Comment by Drup** [comment]
Here's the translation

```
Is this the desired behavior ? 
We might wish for iter and map to pass their parameters in Lwt.apply.
Another solution would be to have two binds, one tail recursive, the other not.
```

Tbh, I'm not sure this comment has any purpose.

**Comment by aantron** [comment]
Thanks!

It seems that comment can be deleted indeed.

Could you split the commit into two, one that does whitespace and renamings, and another that adds the new tests? The reason is that it will make it both easier to review now (not *that* important, but nice), and also easier to read the history later (more important). For the lines that changed only whitespace, a person reading the blame will see something like "whitespace and renamings" and be able to immediately recognize the commit doesn't change logic, and click past it to the previous blame.

**Comment by ryanslade** [comment]
@aantron I've split the changes into three commits, please take another look.

**Comment by aantron** [comment]
Great, thank you!

This brings the coverage of `Lwt_list` up to 100%.

We also probably need to test everything against exceptions raised by `f`, and check that the `_s` functions really run `f` in series, and the `_p` functions really run it in parallel. After solving #347 (currently being worked on), we should probably also add tests checking that these functions are stack-safe. I'll open a new issue about all of this. I think we can check off the `Lwt_list` line in #385 :)

**Comment by aantron** [comment]
The follow-on is #395. Also, cherry-picked these commits onto `working-coverage`, which we need until Bisect_ppx is running on the new jbuilder build system.

**Pull request merged**
